public without sharing class AccountTriggerHelper {
    //Constructor 
    public AccountTriggerHelper() {
        system.debug('Inside AccounttriggerHelper Constructor');
    }
    /**
     * @description updateAccountOwner method updates accounts owner records.
     * @param accList
    */
    public void updateAccountOwner(List<Account> accList){
        //write logic to update the account owner
    }
    /**
     * @description updateAddresses method updates contact address if account address is changed, 
     * if more than record found with same zipcode then it gets random record.
     * @param accList
    */
    public void updateContactAddress(List<Account> accList) {
        //write update contacts logic below
    }
    //Write other methods here as per your requirements

    /******************** ADD MORE METHODS*************************/
}

